apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearch-deployment
  labels:
    app: opensearch
spec:
  replicas: 2
  selector:
    matchLabels:
      app: opensearch
  template:
    metadata:
      labels:
        app: opensearch