apiVersion: v1
kind: Pod
metadata:
  name: producer
  labels:
    app: opensearch
    name: producer

spec:
  containers:
  - name: producer
    image: damslo8421/producer:latest
    imagePullPolicy: Never
    imagePullPolicy: Never
