{{ if .Values.nodesList }}
{{- range $key, $val := .Values.nodesList }}

apiVersion: v1
kind: Service
metadata:
  name: {{ $key }}
  labels:
    app: opensearch
spec:
  ports:
  - port: 9200
    targetPort: 9200
    protocol: TCP
  selector:
    name: {{ $key }}
---
{{- end }}
{{ end }}